name: CI/CD Frontend

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: axelvergara/myapp-frontend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image frontend
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image frontend
        run: docker push $IMAGE_NAME:$IMAGE_TAG
